#!/usr/bin/env python3
"""
Umfassende Umlaut-Korrektur: Findet alle verbliebenen ASCII-Umschreibungen
und ersetzt sie durch echte Umlaute. Arbeitet mit einem breiten Wörterbuch.
"""

import re
from pathlib import Path

# Wörter die NICHT ersetzt werden sollen
PROTECTED = {
    'true', 'false', 'value', 'issue', 'continue', 'queue', 'unique',
    'blue', 'clue', 'due', 'venue', 'rescue', 'argue', 'league',
    'tongue', 'rogue', 'vogue', 'technique', 'fatigue', 'catalogue',
    'dialogue', 'monologue', 'prologue', 'revenue', 'residue',
    'statue', 'virtue', 'tissue', 'pursue', 'ensure', 'endure',
    'figure', 'failure', 'closure', 'exposure', 'measure', 'treasure',
    'pleasure', 'creature', 'feature', 'nature', 'future', 'structure',
    'culture', 'capture', 'picture', 'mixture', 'texture', 'lecture',
    'gesture', 'posture', 'moisture', 'furniture', 'adventure', 'temperature',
    'architecture', 'infrastructure', 'manufacture', 'literature', 'signature',
    'miniature', 'procedure', 'overture', 'departure', 'expenditure',
    'does', 'goes', 'shoes', 'canoes', 'heroes', 'echoes', 'potatoes',
    'tomatoes', 'vetoes', 'zeroes', 'cargoes', 'torpedoes',
    'poem', 'poet', 'poetry', 'phoenix', 'aeroplane', 'maestro',
    'fuel', 'cruel', 'duel', 'gruel', 'jewel', 'samuel',
    'sued', 'glued', 'cued', 'ensued', 'pursued', 'issued', 'valued',
    'continued', 'rescued', 'argued', 'queued',
    'guest', 'guess', 'guide', 'guild', 'guilt', 'guitar', 'guarantee',
    'guard', 'guise', 'guerilla', 'vague',
    'queen', 'query', 'quest', 'question',
    'thread', 'spread', 'bread', 'dead', 'head', 'lead', 'read',
    'instead', 'ahead', 'dread', 'tread', 'steady', 'ready', 'already',
    'routed', 'computed', 'executed', 'distributed', 'contributed',
    'attributed', 'substituted', 'constituted', 'instituted',
    'named', 'framed', 'blamed', 'claimed', 'aimed',
    'based', 'cased', 'phased', 'erased', 'chased',
    'used', 'caused', 'paused', 'abused', 'accused', 'amused',
    'focused', 'confused', 'refused', 'excused',
    'stored', 'explored', 'adored', 'restored', 'ignored', 'scored',
    'include', 'exclude', 'conclude', 'preclude',
    'produce', 'reduce', 'introduce', 'reproduce', 'deduce', 'induce',
    'abuse', 'accuse', 'amuse', 'excuse', 'refuse', 'confuse', 'fuse',
    'minute', 'execute', 'absolute', 'attribute', 'constitute',
    'contribute', 'distribute', 'institute', 'substitute', 'prostitute',
    'route', 'dispute', 'compute', 'commute', 'cute', 'mute', 'brute',
    'pollute', 'dilute', 'salute', 'resolute', 'parachute',
    'acquire', 'require', 'inquire', 'esquire', 'entire',
    'sure', 'pure', 'cure', 'lure', 'mature', 'obscure', 'secure',
    'premature', 'immature', 'insecure',
    'are', 'bare', 'care', 'dare', 'fare', 'hare', 'pare', 'rare',
    'share', 'spare', 'stare', 'ware', 'aware', 'compare', 'declare',
    'prepare', 'square', 'warfare', 'hardware', 'software', 'nightmare',
    'bore', 'core', 'fore', 'gore', 'lore', 'more', 'ore', 'pore',
    'score', 'shore', 'snore', 'sore', 'store', 'swore', 'tore', 'wore',
    'before', 'therefore', 'furthermore', 'explore', 'ignore', 'restore',
    'adore', 'implore', 'offshore', 'anymore', 'moreover',
    'here', 'there', 'where', 'were', 'mere', 'severe', 'sincere',
    'sphere', 'atmosphere', 'interfere', 'somewhere', 'everywhere',
    'nowhere', 'anywhere', 'otherwise',
    'source', 'course', 'force', 'resource', 'discourse',
    'surface', 'interface', 'workspace', 'namespace', 'codebase',
    'database', 'firebase', 'airbase',
    'rule', 'module', 'schedule', 'capsule', 'molecule', 'ridicule',
    'one', 'done', 'none', 'gone', 'bone', 'cone', 'lone', 'tone',
    'zone', 'phone', 'stone', 'alone', 'clone', 'drone', 'ozone',
    'milestone', 'backbone', 'everyone', 'someone', 'anyone',
    'come', 'some', 'home', 'become', 'welcome', 'income', 'outcome',
    'overcome', 'awesome', 'handsome', 'wholesome',
    'like', 'make', 'take', 'name', 'same', 'game', 'came', 'flame',
    'frame', 'blame', 'shame', 'became', 'rename', 'runtime',
    'time', 'line', 'file', 'while', 'code', 'node', 'mode', 'note',
    'type', 'pipe', 'size', 'side', 'wide', 'hide', 'slide',
    'inside', 'outside', 'override', 'provide', 'decide', 'guide',
    'compile', 'profile', 'meanwhile',
    'have', 'give', 'live', 'move', 'love', 'above', 'remove', 'improve',
    'approve', 'prove', 'resolve', 'involve', 'evolve', 'solve',
    'archive', 'directive', 'perspective', 'alternative', 'objective',
    'effective', 'relative', 'native', 'negative', 'positive',
    'sensitive', 'extensive', 'exclusive', 'inclusive', 'recursive',
    'progressive', 'defensive', 'offensive', 'comprehensive',
    'impressive', 'excessive', 'successive', 'aggressive',
    'massive', 'passive', 'expressive', 'interactive', 'reactive',
    'attractive', 'creative', 'narrative', 'comparative', 'cooperative',
    'competitive', 'representative', 'administrative', 'legislative',
    'executive', 'consecutive', 'conservative', 'innovative',
    'productive', 'destructive', 'constructive', 'instructive',
    'selective', 'collective', 'protective', 'detective',
    'respective', 'subjective', 'connective', 'corrective',
    'true', 'blue', 'sue', 'hue', 'cue', 'rue', 'due',
}


def fix_remaining_umlauts(text: str) -> str:
    """Ersetzt verbliebene fehlende Umlaute mit einem umfassenden Wörterbuch."""

    # Sehr breites Wörterbuch für alle häufigen deutschen Wörter
    replacements = [
        # Häufigste fehlende ä-Wörter
        ('Marz', 'März'), ('marz', 'märz'),
        ('Einfuhrung', 'Einführung'), ('einfuhrung', 'einführung'),
        ('Ubung', 'Übung'), ('ubung', 'übung'),
        ('uberhaupt', 'überhaupt'), ('Uberhaupt', 'Überhaupt'),
        ('uber ', 'über '), ('Uber ', 'Über '),
        ('uber-', 'über-'),
        ('daruber', 'darüber'), ('hieruber', 'hierüber'), ('woruber', 'worüber'),
        ('gegenuber', 'gegenüber'), ('Gegenuber', 'Gegenüber'),
        ('zunachst', 'zunächst'), ('Zunachst', 'Zunächst'),
        ('tatsachlich', 'tatsächlich'), ('Tatsachlich', 'Tatsächlich'),
        ('sachlich', 'sachlich'),  # bleibt
        ('nachtraglich', 'nachträglich'),
        ('eigenstandig', 'eigenständig'), ('Eigenstandig', 'Eigenständig'),
        ('vollstandig', 'vollständig'), ('Vollstandig', 'Vollständig'),
        ('selbststandig', 'selbstständig'),
        ('standig', 'ständig'),
        ('standige', 'ständige'), ('standigen', 'ständigen'),
        ('Abhangigkeit', 'Abhängigkeit'), ('abhangig', 'abhängig'),
        ('unabhangig', 'unabhängig'), ('Unabhangig', 'Unabhängig'),
        ('Abhangigkeiten', 'Abhängigkeiten'),
        ('langst', 'längst'), ('langer', 'länger'),
        ('vollstandiges', 'vollständiges'),
        ('fahig', 'fähig'), ('Fahigkeit', 'Fähigkeit'),
        ('Fahigkeiten', 'Fähigkeiten'),
        ('leistungsfahig', 'leistungsfähig'),
        ('nachst', 'nächst'), ('nachste', 'nächste'), ('nachsten', 'nächsten'),
        ('zusatzlich', 'zusätzlich'), ('Zusatzlich', 'Zusätzlich'),
        ('ausdrucklich', 'ausdrücklich'),
        ('naturlich', 'natürlich'), ('Naturlich', 'Natürlich'),
        ('willkurlich', 'willkürlich'),
        ('ausfuhrlich', 'ausführlich'),
        ('ursprunglich', 'ursprünglich'),
        ('regelmassi', 'regelmäßi'),
        ('gleichmassi', 'gleichmäßi'),
        ('massig', 'mäßig'),
        ('schliesslich', 'schließlich'), ('Schliesslich', 'Schließlich'),
        ('ausschliesslich', 'ausschließlich'),
        ('einschliesslich', 'einschließlich'),
        ('anschliessend', 'anschließend'),
        ('Qualitat', 'Qualität'), ('qualitat', 'qualität'),
        ('Paritat', 'Parität'), ('paritat', 'parität'),
        ('Prioritat', 'Priorität'), ('prioritat', 'priorität'),
        ('Identitat', 'Identität'),
        ('Komplexitat', 'Komplexität'),
        ('Funktionalitat', 'Funktionalität'),
        ('Kompatibilitat', 'Kompatibilität'),
        ('Aktivitat', 'Aktivität'),
        ('Stabilitat', 'Stabilität'),
        ('Integritat', 'Integrität'),
        ('Sicherheits', 'Sicherheits'),  # bleibt
        ('Freiheits', 'Freiheits'),  # bleibt
        ('Legitimitat', 'Legitimität'),
        ('Legalitat', 'Legalität'),
        ('Flexibilitat', 'Flexibilität'),
        ('Sensibilitat', 'Sensibilität'),
        ('Spezialitat', 'Spezialität'),
        ('Universitat', 'Universität'),
        ('Realitat', 'Realität'),
        ('Kreativitat', 'Kreativität'),
        ('Normalitat', 'Normalität'),
        ('Moglichkeit', 'Möglichkeit'), ('moglichkeit', 'möglichkeit'),
        ('Moglichkeiten', 'Möglichkeiten'),
        ('moglich', 'möglich'), ('Moglich', 'Möglich'),
        ('ermoglicht', 'ermöglicht'), ('Ermoglicht', 'Ermöglicht'),
        ('ermoglichen', 'ermöglichen'),
        # fur/für
        (' fur ', ' für '), (' Fur ', ' Für '),
        ('fur ', 'für '), ('Fur ', 'Für '),
        # weitere häufige
        ('Veroffentlichung', 'Veröffentlichung'),
        ('veroffentlicht', 'veröffentlicht'),
        ('Ausfuhrung', 'Ausführung'), ('ausfuhrung', 'ausführung'),
        ('Durchfuhrung', 'Durchführung'),
        ('gegenuber', 'gegenüber'),
        ('Ruckgrat', 'Rückgrat'), ('ruckgrat', 'rückgrat'),
        ('Ruckgabe', 'Rückgabe'), ('ruckgabe', 'rückgabe'),
        ('Ruckgabewert', 'Rückgabewert'),
        ('zuruckgegeben', 'zurückgegeben'),
        ('zuruckgeben', 'zurückgeben'),
        ('zuruckzugeben', 'zurückzugeben'),
        ('zuruckzufuhren', 'zurückzuführen'),
        ('zuruckgibt', 'zurückgibt'),
        ('zuruckgeliefert', 'zurückgeliefert'),
        ('Ruckblick', 'Rückblick'),
        ('Ruckgangig', 'Rückgängig'),
        ('Einfuhrung', 'Einführung'),
        ('Ausfuhrungsschleifen', 'Ausführungsschleifen'),
        ('Ausfuhrungslogik', 'Ausführungslogik'),
        ('durchfuhr', 'durchführ'),
        ('ausgefuhrt', 'ausgeführt'),
        ('gefuhrt', 'geführt'),
        ('eingefuhrt', 'eingeführt'),
        ('weitergefuhrt', 'weitergeführt'),
        ('verfugbar', 'verfügbar'), ('Verfugbar', 'Verfügbar'),
        ('Verfugbarkeit', 'Verfügbarkeit'),
        ('Verfugung', 'Verfügung'),
        ('hinzufugen', 'hinzufügen'), ('hinzugefugt', 'hinzugefügt'),
        ('Hinzufugen', 'Hinzufügen'),
        ('pruft', 'prüft'), ('Pruft', 'Prüft'),
        ('prufen', 'prüfen'), ('Prufen', 'Prüfen'),
        ('gepruft', 'geprüft'),
        ('Prufung', 'Prüfung'), ('prufung', 'prüfung'),
        ('Prufungen', 'Prüfungen'),
        ('uberpruft', 'überprüft'),
        ('uberprufen', 'überprüfen'),
        ('Uberprufung', 'Überprüfung'),
        ('Ubersicht', 'Übersicht'), ('ubersicht', 'übersicht'),
        ('Uberblick', 'Überblick'), ('uberblick', 'überblick'),
        ('Uberschrift', 'Überschrift'),
        ('ubernimmt', 'übernimmt'),
        ('ubernommen', 'übernommen'),
        ('Ubernahme', 'Übernahme'),
        ('Ubertragung', 'Übertragung'),
        ('ubertragen', 'übertragen'),
        ('uberschreiten', 'überschreiten'),
        ('uberschritten', 'überschritten'),
        ('uberschreitet', 'überschreitet'),
        ('uberlassen', 'überlassen'),
        ('Ubereinstimmung', 'Übereinstimmung'),
        ('ubereinstimm', 'übereinstimm'),
        ('ubergeben', 'übergeben'), ('Ubergeben', 'Übergeben'),
        ('ubergeordnet', 'übergeordnet'),
        ('uberwiegend', 'überwiegend'),
        ('uberwacht', 'überwacht'),
        ('uberflussig', 'überflüssig'),
        ('Oberflache', 'Oberfläche'), ('oberflache', 'oberfläche'),
        ('Flache', 'Fläche'),
        ('Beschrankung', 'Beschränkung'), ('beschrankt', 'beschränkt'),
        ('einschrankt', 'einschränkt'), ('Einschrankung', 'Einschränkung'),
        ('Veranderung', 'Veränderung'),
        ('verandern', 'verändern'), ('verandert', 'verändert'),
        ('unveranderlich', 'unveränderlich'), ('Unveranderlich', 'Unveränderlich'),
        ('unveranderliche', 'unveränderliche'),
        ('Erklarung', 'Erklärung'), ('erklart', 'erklärt'),
        ('Erweiterbarkeit', 'Erweiterbarkeit'),  # bleibt
        ('auslosend', 'auslösend'), ('auslosen', 'auslösen'), ('auslost', 'auslöst'),
        ('Losung', 'Lösung'), ('losung', 'lösung'),
        ('aufgelost', 'aufgelöst'),
        ('benotigt', 'benötigt'), ('Benotigt', 'Benötigt'),
        ('notig', 'nötig'),
        ('unnotig', 'unnötig'),
        ('vollig', 'völlig'), ('Vollig', 'Völlig'),
        ('gewohnlich', 'gewöhnlich'),
        ('moglich', 'möglich'),
        ('konnte', 'könnte'),
        ('konnten', 'könnten'),
        ('konnen', 'können'), ('Konnen', 'Können'),
        ('konnt', 'könnt'),
        ('wurde', 'würde'),  # careful - only in specific context
        ('wurden', 'würden'),
        ('musste', 'müsste'),
        ('mussen', 'müssen'), ('Mussen', 'Müssen'),
        ('mussten', 'müssten'),
        ('genugt', 'genügt'), ('genugen', 'genügen'),
        ('Begrundung', 'Begründung'), ('begrundet', 'begründet'),
        ('grundet', 'gründet'),
        ('grundlich', 'gründlich'),
        ('Grunde', 'Gründe'), (' grunde', ' gründe'),
        ('grundsatzlich', 'grundsätzlich'),
        ('gultig', 'gültig'), ('ungultig', 'ungültig'),
        ('kunftig', 'künftig'), ('zukunftig', 'zukünftig'),
        ('Kurzlich', 'Kürzlich'),
        ('Kurzung', 'Kürzung'), ('gekurzt', 'gekürzt'),
        ('Stuck', 'Stück'), ('stuck', 'stück'),
        ('Herzstuck', 'Herzstück'),
        ('Ruckgrat', 'Rückgrat'),
        ('unterstutzt', 'unterstützt'), ('unterstutzen', 'unterstützen'),
        ('Unterstutzung', 'Unterstützung'),
        ('Schlussel', 'Schlüssel'), ('schlussel', 'schlüssel'),
        ('Schlusselkette', 'Schlüsselkette'),
        ('Einstiegspunkt', 'Einstiegspunkt'),  # bleibt
        ('Ausfuhrung', 'Ausführung'),
        ('ausfuhrbar', 'ausführbar'),
        ('Ausfuhrungsschicht', 'Ausführungsschicht'),
        ('ausfuhrt', 'ausführt'),
        ('haufi', 'häufi'),
        ('haufig', 'häufig'),
        ('haufigste', 'häufigste'),
        ('nachlass', 'nachläss'),
        ('Zusammenfuhrung', 'Zusammenführung'),
        ('zusammengefuhrt', 'zusammengeführt'),
        ('hinzugefugt', 'hinzugefügt'),
        ('eingefugt', 'eingefügt'),
        ('ausgefuhrt', 'ausgeführt'),
        ('durchgefuhrt', 'durchgeführt'),
        ('weiterfuhr', 'weiterführ'),
        ('eingefuhrt', 'eingeführt'),
        ('stattfind', 'stattfind'),  # bleibt
        ('Geschaeftslogik', 'Geschäftslogik'),
        ('Geschaftslogik', 'Geschäftslogik'),
        ('nutzlich', 'nützlich'),
        ('Worterbuch', 'Wörterbuch'), ('worterbuch', 'wörterbuch'),
        ('Horner', 'Hörner'),
        ('storend', 'störend'),
        ('zerstort', 'zerstört'),
        ('grosse ', 'große '), ('grossen ', 'großen '), ('grosser ', 'großer '),
        ('grosses ', 'großes '), ('grossem ', 'großem '),
        ('Grosse ', 'Große '), ('Grossen ', 'Großen '), ('Grosser ', 'Großer '),
        ('Grosses ', 'Großes '),
        ('ausserhalb', 'außerhalb'), ('Ausserhalb', 'Außerhalb'),
        ('ausserdem', 'außerdem'), ('Ausserdem', 'Außerdem'),
        ('ausserst', 'äußerst'),
        ('ausser ', 'außer '), ('Ausser ', 'Außer '),
        ('aussen', 'außen'), ('Aussen', 'Außen'),
        ('heisst', 'heißt'),
        ('weiss ', 'weiß '), ('Weiss ', 'Weiß '),
        ('Strasse', 'Straße'), ('strasse', 'straße'),
        ('schliessen', 'schließen'), ('schliesst', 'schließt'),
        ('anschliessend', 'anschließend'),
        ('stossen', 'stoßen'), ('angestossen', 'angestoßen'),
        # Residual patterns
        ('Fahigkeit', 'Fähigkeit'),
        ('erklarung', 'erklärung'),
        ('Oberflache', 'Oberfläche'),
        ('Eingangig', 'Eingängig'),
    ]

    for old, new in replacements:
        text = text.replace(old, new)

    return text


def process_file(filepath: Path):
    print(f"Verarbeite: {filepath}")
    content = filepath.read_text(encoding='utf-8')
    new_content = fix_remaining_umlauts(content)

    # Zähle Änderungen
    changes = 0
    for a, b in zip(content, new_content):
        if a != b:
            changes += 1
    if len(new_content) != len(content):
        changes += abs(len(new_content) - len(content))

    print(f"  {changes} Zeichenänderungen")
    filepath.write_text(new_content, encoding='utf-8')


if __name__ == '__main__':
    base = Path(__file__).resolve().parent
    process_file(base / "BUCH_CLAW_CODE_ARCHITEKTUR.md")
    print("Fertig!")
